### ISSUE TITLE
Unicode probléma

### ISSUE THREAD

**Issue by davidpokorni** [Teaching-projects/SZE-MOSZE-2020-GitCraft#13]
@hegyhati Beleütköztünk egy olyan problémába a game osztály pálya kiírásánál, hogy amikor lefordítjuk a kódot, akkor a unicode karaktereket nem jól jeleníti meg. Ez alatt azt értem, hogy a megfelelő karakter helyett csak össze vissza betűket ír ki. Viszont ha terminálba külön ki echozuk az adott unicode-ot akkor tökéletesen megjelenik, Ebben szeretnénk segítséget kérni.

**Comment by hegyhati** [comment]
Arra tippelnek, hogy ahol nem jol jelenik meg (hol?) ott a terminal nem kezel utf8-at. Esetleg annak a beallitasai kozott nezegetnem. A forditonak nem szabadna, hogy problemat okozzon. 2020-ban. (a terminalnak sem, de... )
