### ISSUE TITLE
Második videó

### ISSUE THREAD

**Issue by davidpokorni** [Teaching-projects/SZE-MOSZE-2020-GitCraft#17]
@hegyhati Egy olyan problémába ütköztünk, hogy a második, 2 perces videót nem engedi fel pusholni a github mert a maximális fájl méret amit enged 100MB, a miénk pedig 140MB. Erre valami ötletet esetleg tudnál adni?
Előre is köszönjük!

**Comment by hegyhati** [comment]
Hat rendereljetek ujra, vagjatok ket darabra, stb. Azert ha siman ujrarenderelitek, ennek le kellene mennie. Foleg ha nem 4k.
