### ISSUE TITLE
Final report

### ISSUE THREAD

**Issue by davidpokorni** [Teaching-projects/SZE-MOSZE-2020-GitCraft#19]
@hegyhati Elkészültünk a videókkal és a Report.md-vel, be lettek merge-vel a masterre.

**Comment by Patorik** [comment]
Bocsánat, a relatív érdemjegyeknél 4-eseket írtunk, de 0-nak értjük.

**Comment by oliverosz** [comment]
A renderer még jó lett volna ha elkészül, meg unit tesztekből is lehetne több, de azért egy 5-ös alát megajánlok mindhármotoknak.
