### ISSUE TITLE
Documentation PR nyitás

### ISSUE THREAD

**Issue by davidpokorni** [Teaching-projects/SZE-MOSZE-2020-GitCraft#9]
@hegyhati Azt szeretném kérdezni, hogy a unit test PR-t és a documentation PR-t megnyithatjuk-e úgy, hogy a refaktor rész még nincsen készen, vagy ezeket csak a refaktor elkészülte után lenne célszerű? A határidő miatt kérdezzük.

**Comment by hegyhati** [comment]
Szerintem erre mar mashol valasozltam, de nyugodtan. Arra van a git, hogy lehessen parhuzasmosan dolgozni dolgokon. Hogy Nektek hogy jobb, Ti latjatok. a harmadik koros dolgoknak kell mind meglenniuk, hogy  ezek mehessenek.

**Comment by davidpokorni** [comment]
Rendben, köszönöm.
